### ISSUE TITLE
Finetuned weights

### ISSUE THREAD

**Issue by barthelemymp** [phbradley/TCRdock#5]
Hi,

Thank you for the repo and and the paper!
Are the weights of the finetuned model available somewhere ?

Best

**Comment by phbradley** [comment]
Hi, thanks for your interest, and sorry for the slow reply! I've been reworking things to make the protocol faster and I think also more accurate, using a single alphafold simulation per TCR:pMHC target rather than 3, and a new set of fine-tuned weights. If you check out the google colab notebook on github 

https://github.com/phbradley/TCRdock/blob/main/tcrdock_colab_pipeline_v1.ipynb

or even better test it out on colab:

https://colab.research.google.com/github/phbradley/TCRdock/blob/main/tcrdock_colab_pipeline_v1.ipynb
 
it has details on the new fine-tuned parameter set (dropbox link) and command line for setup. Note that these new parameters need to be used with the new setup, in particular the `--new_docking` flag to the `setup_for_alphafold.py` script as shown in the colab notebook.

Let me know if you have any questions!

**Comment by barthelemymp** [comment]
Thank you very  much. This is very helpfull
