### ISSUE TITLE
CDR RSME 

### ISSUE THREAD

**Issue by eleven-0325** [phbradley/TCRdock#8]
Hello,
I followed the suggested command lines on the git to run TCRdock.

when I want to test CDR RMSD based on generated structures and benchmarks, how should this script to be written?

**Comment by phbradley** [comment]
Hi there,
Thanks for trying the software. For model evaluation, it really depends on what you are interested in. There are so many different metrics. You could try superimposing on the MHC and then calculating RMSD over the CDR loops. But many people prefer contact-based metrics. The CAPRI docking community has lots of evaluation tools that you might want to consider. It is also a good idea just to look at the models in a viewer like PyMOL and see how they compare to the native structures.

Since there are so many different choices, there is not an "evaluation" script in the TCRdock code base. The scope is limited to model building. If you can describe a very specific calculation that you want to do, there may be some functions (like for superposition) that I could suggest.
Take care,
Phil

**Comment by eleven-0325** [comment]
@phbradley   Thank you very much for your answer. I greatly appreciate your assistance and once again, thank you for your hard work.
